config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    # Apps externas
    path("django_plotly_dash/", include("django_plotly_dash.urls")),
    path("select2/", include("django_select2.urls")),
]

urlpatterns += [
    # Apps locales
    # path(
    #     "", TemplateView.as_view(template_name="pages/home.html"), name="home"
    # ),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("sis_prototipo.apps.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("", include("sis_prototipo.apps.core.urls", namespace="core")),
    path("vectores/", include("sis_prototipo.apps.vectores.urls", namespace="vectores")),
    path("geo/", include("sis_prototipo.apps.geo.urls", namespace="geo")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

sis_prototipo/apps/core/urls.py
from django.urls import path

from sis_prototipo.apps.core.views import HomeView

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
]

sis_prototipo/apps/geo/urls.py
from django.urls import path

from sis_prototipo.apps.geo.views import ExploracionAppView

app_name = "geo"

urlpatterns = [
    path("exploracion", ExploracionAppView.as_view(), name="exploracion"),
]

sis_prototipo/apps/users/urls.py
from django.urls import path

from sis_prototipo.apps.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

sis_prototipo/apps/vectores/urls.py
from django.urls import path

from sis_prototipo.apps.vectores.views import (
    AnalisisDengueAppView,
    ClusteringDengueAppView,
    SeriesDengueAppView,
)

app_name = "vectores"

urlpatterns = [
    path(
        "analisis_dengue",
        AnalisisDengueAppView.as_view(),
        name="analisis_dengue",
    ),
    path(
        "clustering_dengue",
        ClusteringDengueAppView.as_view(),
        name="clustering_dengue",
    ),
    path(
        "tablero_dengue",
        SeriesDengueAppView.as_view(),
        name="series_dengue",
    )
]

sis_prototipo/apps/core/models.py
# Create your models here.

sis_prototipo/apps/geo/models.py
from django.conf import settings
from django.contrib.contenttypes.models import ContentType

from django.contrib.gis.db import models


class DivisionGeografica(models.Model):
    geom = models.MultiPolygonField(srid=settings.CRS)
    cve_ent = models.CharField(max_length=2)
    area = models.FloatField()
    densidad = models.FloatField()
    pobtot = models.PositiveIntegerField(
        "Población total",
        null=True,
        blank=True,
    )
    pobmas = models.PositiveIntegerField(
        "Población masculina",
        null=True,
        blank=True,
    )
    pobfem = models.PositiveIntegerField(
        "Población femenina",
        null=True,
        blank=True,
    )

    class Meta:
        abstract = True

class Entidad(DivisionGeografica):
    cvegeo = models.CharField(max_length=2, primary_key=True)
    nomgeo = models.CharField(max_length=80)

    def __str__(self):
        return self.nomgeo

    class Meta:
        ordering = ["nomgeo"]


class Municipio(DivisionGeografica):
    geom = models.MultiPolygonField(srid=settings.CRS)
    cvegeo = models.CharField(max_length=5, primary_key=True)
    nomgeo = models.CharField(max_length=80)
    cve_ent = models.CharField(max_length=2)
    cve_mun = models.CharField(max_length=3)
    entidad = models.ForeignKey(Entidad, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.nomgeo

    class Meta:
        ordering = ["nomgeo"]


class Localidad(DivisionGeografica):
    PLANO_TIPO = ((0, "No"), (1, "Si"), (2, "Croquis"))
    AMBITO_TIPO = ((0, "No Aplica"), (1, "Urbana"), (2, "Rural"))
    cvegeo = models.CharField(max_length=9, primary_key=True)
    nomgeo = models.CharField(max_length=120)
    cve_ent = models.CharField(max_length=2)
    cve_mun = models.CharField(max_length=3)
    cve_loc = models.CharField(max_length=4)
    ambito = models.PositiveSmallIntegerField(choices=AMBITO_TIPO, null=True)
    plano = models.PositiveSmallIntegerField(choices=PLANO_TIPO, null=True)
    puntual = models.BooleanField(default=False)
    municipio = models.ForeignKey(
        Municipio, on_delete=models.SET_NULL, null=True
    )
    def __str__(self):
        return self.nomgeo

    class Meta:
        ordering = ["nomgeo"]


class Manzana(DivisionGeografica):
    # Definicion de elementos para campo de eleccion
    AMBITO_TIPO = ((0, "No Aplica"), (1, "Urbana"), (2, "Rural"))
    MANZANA_TIPO = (
        (0, "No Aplica"),
        (1, "Típica"),
        (2, "Atípica"),
        (3, "Contenedora"),
        (4, "Contenida"),
        (5, "Económica"),
        (6, "Edificio-Manzana"),
        (7, "Glorieta"),
        (8, "Parque o Jardín"),
        (9, "Camellón"),
        (10, "Bajo Puente"),
    )

    cvegeo = models.CharField(max_length=16, primary_key=True)
    cve_ent = models.CharField(max_length=2)
    cve_mun = models.CharField(max_length=3)
    cve_loc = models.CharField(max_length=4)
    cve_ageb = models.CharField(max_length=4)
    cve_mza = models.CharField(max_length=3)
    ambito = models.PositiveSmallIntegerField(choices=AMBITO_TIPO)
    tipomza = models.PositiveSmallIntegerField(choices=MANZANA_TIPO)
    localidad = models.ForeignKey(
        Localidad, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.cvegeo

sis_prototipo/apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for SIS-prototipo.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

sis_prototipo/apps/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

sis_prototipo/apps/vectores/forms.py
from crispy_forms.bootstrap import Alert, Field, Tab, TabHolder
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Fieldset, Layout, Submit
from django.forms import ModelChoiceField, ModelForm, TextInput
from django_select2.forms import ModelSelect2Widget
from leaflet.forms.widgets import LeafletWidget

from sis_prototipo.apps.geo.models import Entidad, Localidad, Municipio
from sis_prototipo.apps.vectores.models import Vector


class VectorForm(ModelForm):
    des_edo_res = ModelChoiceField(
        queryset=Entidad.objects.all(),
        label="Entidad",
        widget=ModelSelect2Widget(
            model=Entidad,
            search_fields=["nomgeo__icontains"],
        ),
    )
    des_mpo_res = ModelChoiceField(
        queryset=Municipio.objects.all(),
        label="Municipio",
        widget=ModelSelect2Widget(
            model=Municipio,
            search_fields=["nomgeo__icontains"],
            dependent_fields={"des_edo_res": "entidad"},
        ),
    )

    des_loc_res = ModelChoiceField(
        queryset=Localidad.objects.all(),
        label="Localidad",
        widget=ModelSelect2Widget(
            model=Localidad,
            search_fields=["nomloc__icontains"],
            dependent_fields={"des_mpo_res": "municipio"},
        ),
    )

    class Meta:
        model = Vector
        labels = {
            "nss": "Número de seguridad social",
            "ide_nom": "Nombre",
            "ide_ape_pat": "Apellido paterno",
            "ide_ape_mat": "Apellido materno",
            "ide_sex": "Sexo",
            "num_ext": "Número exterior",
            "num_int": "Número interior",
            "ide_cal": "Calle",
            "ide_calle1": "Entre calle",
            "ide_calle2": "y calle",
            "ide_col": "Colonia",
            "ide_cp": "Código postal",
            "fec_sol_aten": "Fecha de solicitud de atención",
            "des_diag_final": "Diagnóstico final",
            "geometry": "Punto geográfico",
        }

        exclude = (
            "creado",
            "coords",
            "precision",
            "cve_diag_final",
            "activo",
            "peligro",
        )

        widgets = {
            "fec_sol_aten": TextInput(attrs={"type": "date"}),
            "geometry": LeafletWidget(),
        }

    def __init__(self, *args, **kwargs):
        super(VectorForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.add_input(
            Submit("submit", "Guardar", css_class="btn-success")
        )
        self.helper.form_class = "form-horizontal"
        self.helper.help_text_inline = True
        self.helper.layout = Layout(
            Fieldset(
                "Datos generales",
                Field("nss"),
                Field("ide_nom"),
                Field("ide_ape_pat"),
                Field("ide_ape_mat"),
                Field("ide_sex"),
            ),
            Fieldset(
                "Diagnóstico", Field("fec_sol_aten"), Field("des_diag_final")
            ),
            Fieldset(
                "Información geográfica",
                Alert(
                    content="<strong>Atención: </strong> Poner dirección o punto geográfico, no los dos",
                    css_class="alert alert-warning",
                ),
                TabHolder(
                    Tab(
                        "Geoposición",
                        "geometry",
                    ),
                    Tab(
                        "Direccion",
                        "num_ext",
                        "num_int",
                        "ide_cal",
                        "ide_calle1",
                        "ide_calle2",
                        "ide_cp",
                        "ide_col",
                        "des_edo_res",
                        "des_mpo_res",
                        "des_loc_res",
                    ),
                ),
            ),
        )

sis_prototipo/apps/core/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'core/home.html'

sis_prototipo/apps/embarazadas/views.py
# Create your views here.

sis_prototipo/apps/geo/views.py
from django.views.generic import TemplateView
from rest_framework.generics import ListAPIView

from sis_prototipo.apps.geo.models import Entidad
from sis_prototipo.apps.geo.serializers import EntidadGeoSerializer


class EntidadListView(ListAPIView):
    queryset = Entidad.objects.all()
    serializer_class = EntidadGeoSerializer


class ExploracionAppView(TemplateView):
    template_name = "geo/exploracion.html"

sis_prototipo/apps/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

sis_prototipo/apps/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

sis_prototipo/apps/vectores/views.py
from django.views.generic import TemplateView

from sis_prototipo.apps.geo.models import Entidad
from sis_prototipo.apps.vectores.dash_apps import (
    analisis_dengue,
    clustering_dengue,
    series_dengue
)
from sis_prototipo.apps.vectores.dash_apps.utils import entidades_opciones_dropdown


class DashAppView(TemplateView):
    template_name = "vectores/aplicacion_dash.html"
    dash_app = None
    titulo = None

    def get_context_data(self, **kwargs):
        context = super(DashAppView, self).get_context_data(**kwargs)
        context["dash_app"] = self.dash_app.nombre
        context["titulo"] = self.titulo
        return context


class AnalisisDengueAppView(DashAppView):
    dash_app = analisis_dengue
    titulo = "Análisis de datos"


class ClusteringDengueAppView(DashAppView):
    dash_app = clustering_dengue
    titulo = "Clustering de Dengue"


class SeriesDengueAppView(DashAppView):
    dash_app = series_dengue
    titulo = "Análisis de series de tiempo"

sis_prototipo/templates/core/base.html
<!DOCTYPE HTML>
<html lang="">
<head>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    {% block header %}{% endblock %}
    {% block extra_header %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static "core/css/main.css" %}"></link>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a href="#" class="navbar-brand">Prototipo</a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navbarCollapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        <a href="{% url 'core:home' %}" class="nav-link">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">Manual</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'geo:exploracion' %}" class="nav-link">Exploración geoespacial</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Dengue</a>
                        <div class="dropdown-menu dropdown-menu-dark">
                            <a href="{% url 'vectores:analisis_dengue' %}" class="dropdown-item">Análisis
                                geoespacial</a>
                            <a href="{% url 'vectores:clustering_dengue' %}" class="dropdown-item">Clustering</a>
                            <a href="{% url 'vectores:series_dengue' %}" class="dropdown-item">Tablero de datos de
                                dengue</a>
{#                          <a href="{% url 'vectores:leaflet' %}" class="dropdown-item">leafletpyth</a>#}
                            {#                            <div class="dropdown-divider"></div>#}
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Cáncer</a>
                        <div class="dropdown-menu dropdown-menu-dark">
                            <a href="#" class="dropdown-item">Segmentación semántica</a>
                            <div class="dropdown-divider"></div>
                            <a href="#" class="dropdown-item">Trash</a>
                        </div>
                    </li>
                </ul>

                <ul class="nav navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="#" class="nav-link">Acerca de</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Cuenta</a>
                        <div class="dropdown-menu  dropdown-menu-dark dropdown-menu-end">
                            <a href="#" class="dropdown-item">Perfil</a>
                            <a href="#" class="dropdown-item">Configuración</a>
                            <div class="dropdown-divider"></div>
                            <a href="#" class="dropdown-item">Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

{% block content %}{% endblock %}
{% block footer %}{% endblock %}
{% block js %}{% endblock %}
</body>
{% block post_body %}{% endblock %}
</html>

sis_prototipo/templates/core/home.html
{% extends "core/base.html" %}

{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block header %}
    <link rel="stylesheet" type="text/css" href="{% static "core/css/inicio.css" %}"></link>
{% endblock %}

{% block title %}Inicio{% endblock %}

{% block content %}
    <h1>Inicio</h1>
    <div id="container">
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum
            tortor
            quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.
            Aenean
            ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra.
            Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget
            tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis
            pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu
            vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor,
            facilisis
            luctus, metus</p>

        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum
            tortor
            quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.
            Aenean
            ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra.
            Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget
            tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis
            pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu
            vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor,
            facilisis
            luctus, metus</p>

        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum
            tortor
            quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.
            Aenean
            ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra.
            Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget
            tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis
            pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu
            vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor,
            facilisis
            luctus, metus</p>
    </div>

{% endblock %}